[workspace]
members = [
    "crates/raft",
    "crates/neurod", 
    "crates/neuroctl",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.39", features = ["derive", "env"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
